# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-07 03:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TextEditor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='TextEditor.MUser'),
            preserve_default=False,
        ),
    ]
