# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-07 05:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TextEditor', '0002_document_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='muser',
            name='picture',
        ),
    ]
