# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-28 22:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TextEditor', '0003_remove_muser_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='File',
        ),
    ]
