# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-29 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextEditor', '0004_remove_document_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('data_type', models.CharField(max_length=50)),
                ('data_file', models.FileField(upload_to=b'')),
            ],
        ),
    ]
